---
name: Run tests
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-13
          - macos-14
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up
        uses: ./.github/actions/setup
      - name: Run unit tests
        shell: bash
        run: ./development/cli/execute_tests.bash
